"""
pyql_to_cypher.py
─────────────────
Translates a PyQL operation list into a single Cypher query
for execution against a Neo4j Freebase backend.

Fixes applied:
  - Bug 1: ORDER BY variable now included in RETURN clause (avoids DISTINCT error)
  - Bug 2: xsd:float literals handled as literal values, not node references
  - Bug 3: Entity node label unified to FBNode
  - Bug 4: rel_to_neo4j_type uses double underscore (lowercase) to match Neo4j schema
"""

import re
from typing import List, Optional


# ── helpers ───────────────────────────────────────────────────────────────────

def rel_to_neo4j_type(relation: str) -> str:
    """
    Convert Freebase relation name to Neo4j relationship type.
    e.g. "people.person.date_of_birth" → "people__person__date_of_birth"
    """
    return relation.replace(".", "_").upper()


def is_entity(token: str) -> bool:
    """Check if token is a Freebase entity MID (e.g. m.0fjvv, g.125abc)."""
    return bool(re.match(r'^[mg]\.[0-9a-zA-Z_]+$', token))


def is_variable(token: str) -> bool:
    """Check if token is a PyQL variable (starts with ?)."""
    return token.startswith("?")


def is_literal(token: str) -> bool:
    """
    Check if token is a literal value (xsd:float, quoted string, number).
    e.g. '"8000.0"^^xsd:float', '"2000-01-01"', '42'
    """
    return (
        token.startswith('"') or
        token.startswith("'") or
        '^^xsd:' in token or
        re.match(r'^-?[0-9]+(\.[0-9]+)?$', token) is not None
    )


def var_name(token: str) -> str:
    """Strip leading ? from variable name for use in Cypher."""
    return token.lstrip("?")


def mid_to_cypher_id(mid: str) -> str:
    """
    Convert Freebase MID to a safe Cypher identifier.
    e.g. "m.0fjvv" → "m_0fjvv"
    """
    return mid.replace(".", "_")


def literal_to_cypher(token: str) -> str:
    """
    Convert a literal token to a Cypher-safe representation.
    Strips xsd type annotation and returns the raw value.
    e.g. '"8000.0"^^xsd:float' → '8000.0'
         '"2000-01-01"'        → '"2000-01-01"'
    """
    if '^^xsd:' in token:
        # Extract the value part before ^^
        value = token.split('^^')[0].strip('"').strip("'")
        return value
    return token


# ── parser ────────────────────────────────────────────────────────────────────

def parse_op(op_str: str):
    """
    Parse a single PyQL operation string into (op_name, args).
    Handles quoted arguments that may contain commas.
    """
    op_str = op_str.strip().rstrip(")")
    paren_idx = op_str.index("(")
    op_name = op_str[:paren_idx].strip()
    args_str = op_str[paren_idx + 1:].strip()

    # Safe split: respect quoted strings
    args = []
    current = []
    in_quote = None
    for char in args_str:
        if in_quote:
            current.append(char)
            if char == in_quote:
                in_quote = None
        elif char in ('"', "'"):
            in_quote = char
            current.append(char)
        elif char == ',' :
            args.append("".join(current).strip())
            current = []
        else:
            current.append(char)
    if current:
        args.append("".join(current).strip())

    return op_name, args

def _dedup_add_facts(pyql_ops: List[str]) -> List[str]:
    """
    Remove redundant add_fact operations before translation.
 
    Two types of redundancy are handled:
 
    1. Exact duplicates:
       add_fact(A, rel, B)  +  add_fact(A, rel, B)  →  keep one
 
    2. Bidirectional inverse pairs (forward + backward encoding of the same
       entity pair, as sometimes generated by the LLM):
       add_fact(A, rel1, B)  +  add_fact(B, rel2, A)  →  keep only the first
 
       Example (Index 11 — virizion):
         add_fact(m.010g06mg, fictional_universe.character_species.characters_of_this_species, ?character)
         add_fact(?character, fictional_universe.fictional_character.species, m.010g06mg)
       → second is dropped because subject/object are swapped relative to the first.
 
    Non-add_fact operations are passed through unchanged.
    """
    result = []
    seen_facts = []   # list of (s, rel, o) tuples already added
    seen_pairs = []   # list of (s, o) frozensets already seen in add_fact
 
    for op_str in pyql_ops:
        try:
            op_name, args = parse_op(op_str)
        except Exception:
            result.append(op_str)
            continue
 
        if op_name != "add_fact" or len(args) < 3:
            result.append(op_str)
            continue
 
        s, rel, o = args[0], args[1], args[2]
        triple = (s, rel, o)
        pair   = frozenset([s, o])
 
        # Drop exact duplicate
        if triple in seen_facts:
            continue
 
        # Drop bidirectional inverse: if we already have a fact with the same
        # two endpoints (regardless of direction), skip this one.
        if pair in seen_pairs:
            continue
 
        seen_facts.append(triple)
        seen_pairs.append(pair)
        result.append(op_str)
 
    return result


# ── main translator class ─────────────────────────────────────────────────────

class PyQLToCypher:
    """
    Stateful translator: accumulates MATCH/WHERE clauses from PyQL ops,
    then emits a single Cypher query string when translate() is called.
    """

    def translate(self, pyql_ops: List[str]) -> str:
        self._reset()
        pyql_ops = _dedup_add_facts(pyql_ops)


        for op_str in pyql_ops:
            try:
                op_name, args = parse_op(op_str)
            except Exception as e:
                raise ValueError(f"Cannot parse PyQL op: '{op_str}' — {e}")

            if op_name == "add_fact":
                self._handle_add_fact(args)
            elif op_name == "add_type_constrain":
                self._handle_add_type_constrain(args)
            elif op_name == "add_filter":
                self._handle_add_filter(args)
            elif op_name == "add_count":
                self._handle_add_count(args)
            elif op_name == "add_max":
                self._handle_add_max(args)
            elif op_name == "add_min":
                self._handle_add_min(args)
            elif op_name == "set_answer":
                self._handle_set_answer(args)
            else:
                raise ValueError(f"Unknown PyQL operation: {op_name}")

        return self._build_cypher()

    # ── internal state ────────────────────────────────────────────────────────

    def _reset(self):
        self.match_clauses: List[str] = []
        self.where_clauses: List[str] = []
        self.return_var: Optional[str] = None
        self.count_var: Optional[str] = None
        self.count_target: Optional[str] = None
        self.order_by: Optional[str] = None
        self.order_var: Optional[str] = None
        self.limit_one: bool = False
        self.entity_nodes: dict = {}

    # ── op handlers ──────────────────────────────────────────────────────────

    def _handle_add_fact(self, args: List[str]):
        s, rel, o = args[0], args[1], args[2]
        rel_type = rel_to_neo4j_type(rel)

        s_cypher = self._node_ref(s)

        # Bug 2 fix: if object is a literal, use WHERE clause instead of node pattern
        if is_literal(o):
            # We need a dummy variable to match against, then filter in WHERE
            lit_var = f"lit_{len(self.where_clauses)}"
            self.match_clauses.append(
                f"MATCH ({s_cypher})-[:`{rel_type}`]->({lit_var})"
            )
            self.where_clauses.append(f"{lit_var} = {literal_to_cypher(o)}")
        else:
            o_cypher = self._node_ref(o)
            self.match_clauses.append(
                f"MATCH ({s_cypher})-[:`{rel_type}`]->({o_cypher})"
            )

    

    def _handle_add_type_constrain(self, args: List[str]):
        fb_type, var = args[0], args[1]
        v = var_name(var)
        self.where_clauses.append(f"'{fb_type}' IN {v}.types")
        
        

    def _handle_add_filter(self, args: List[str]):
        var, op, value = args[0], args[1], args[2]
        v = var_name(var)
        
        # 标准化不等号
        if op == "!=":
            op = "<>"
        
        # 如果 value 是 entity MID，比较节点的 mid 属性
        if is_entity(value):
            self.where_clauses.append(f"{v}.mid {op} '{value}'")
        elif is_literal(value):
            self.where_clauses.append(f"{v} {op} {literal_to_cypher(value)}")
        else:
            self.where_clauses.append(f"{v} {op} {value}")
        
    def _handle_add_count(self, args: List[str]):
        self.count_target = var_name(args[0])
        self.count_var = var_name(args[1])

    def _handle_add_max(self, args: List[str]):
        self.order_var = var_name(args[0])
        self.order_by = "DESC"
        self.limit_one = True

    def _handle_add_min(self, args: List[str]):
        self.order_var = var_name(args[0])
        self.order_by = "ASC"
        self.limit_one = True

    def _handle_set_answer(self, args: List[str]):
        self.return_var = var_name(args[0])

    # ── node reference helper ────────────────────────────────────────────────

    def _node_ref(self, token: str) -> str:
        if is_variable(token):
            return var_name(token)

        if is_entity(token):
            cypher_id = mid_to_cypher_id(token)
            if cypher_id not in self.entity_nodes:
                self.entity_nodes[cypher_id] = token
                # Bug 3 fix: unified label FBNode
                return f"{cypher_id}:FBNode {{mid: '{token}'}}"
            else:
                return cypher_id

        # Fallback: unknown token type
        raise ValueError(f"Unrecognized token in add_fact: '{token}'. "
                         f"Expected a MID (m.xxx), variable (?var), or literal.")

    # ── cypher builder ────────────────────────────────────────────────────────

    def _build_cypher(self) -> str:
        lines = []

        for m in self.match_clauses:
            lines.append(m)

        if self.where_clauses:
            lines.append("WHERE " + "\n  AND ".join(self.where_clauses))

        # RETURN clause
        if self.count_var and self.count_target:
            lines.append(
                f"RETURN COUNT(DISTINCT {self.count_target}) AS {self.count_var}"
            )
        elif self.return_var:
            # Bug 1 fix: include order_var in RETURN to avoid DISTINCT error
            if self.order_by and self.order_var:
                order_expr = f"{self.order_var}.{self.order_var}"
                lines.append(f"RETURN DISTINCT {self.return_var}, {order_expr}")
            else:
                lines.append(f"RETURN DISTINCT {self.return_var}")
        else:
            lines.append("RETURN *")

        # ORDER BY / LIMIT
        if self.order_by and self.order_var:
            order_expr = f"{self.order_var}.{self.order_var}"
            lines.append(f"ORDER BY {order_expr} {self.order_by}")
        if self.limit_one:
            lines.append("LIMIT 1")

        return "\n".join(lines)
